name: Test, Build and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '12.x'
    - uses: subosito/flutter-action@v2.10.0
      with:
        channel: "stable"
    - run: flutter pub get
    - run: flutter test